### ISSUE TITLE
no sitemap in dist folder 

### ISSUE THREAD

**Issue by msfm360** [jbaubree/vite-plugin-pages-sitemap#300] opened 2023-04-23 08:54 UTC
![image](https://user-images.githubusercontent.com/50640440/233829863-d35ab1d9-86a4-4cca-bed0-bf779d180994.png)

**Comment by jbaubree** [comment] 2023-04-30 13:29
When you are running in dev mode, sitemap.xml and robots.txt files are generated in your public folder

**Comment by jbaubree** [comment] 2023-04-30 13:53
@msfm360 make sure to follow [Getting started guide](https://github.com/jbaubree/vite-plugin-pages-sitemap#getting-started) too

**Comment by jbaubree** [comment] 2023-05-13 16:17
Closing for inactivity. Feel free to reopen if this issue persists

**Comment by kg-pb** [comment] 2023-06-22 02:38
I'm having same issue. Followed the getting started guide, but folders(dist, public) doesn't have sitemap.xml

**Comment by recoiladam** [comment] 2023-09-06 04:24
This is still an ongoing problem. There is no sitemap.xml in the `dist` or `public` directories.

Here's my full vite.config.js file:

```
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import eslintPlugin from 'vite-plugin-eslint'
import Pages from 'vite-plugin-pages'
import generateSitemap from 'vite-plugin-pages-sitemap'

const config = defineConfig({
  base: './',
  build: {
    rollupOptions: {
      output: {
        format: 'es',
        strict: false,
        entryFileNames: "[name].js",
        dir: 'dist/'
      }
    }
  },
  plugins: [
    vue(),
    eslintPlugin(),
    Pages({
      onRoutesGenerated: routes => (generateSitemap({
        hostname: 'https://farmflight.us/',
        routes: ['/', '/about', '/analytics', '/imagery', '/contact', '/team', '/privacy', '/terms'],
        readable: true,
        filename: 'sitemap.xml',
        allowRobots: true,
        priority: 1.0,
        changefreq: 'weekly'
      }))
    })
  ],
  resolve: {
    alias: [
      {
        find: '@',
        replacement: fileURLToPath(new URL('./src', import.meta.url))
      }
    ]
  }
})

export default config

```

**Comment by jbaubree** [comment] 2023-09-06 05:39
Hi @recoiladam 👋
Can you provide me a repo with reproduction of your issue?

**Comment by recoiladam** [comment] 2023-09-06 05:42
> 

You need to stop asking people for their code. The majority of us developers are working on private projects that we cannot share publicly or even privately with someone that is not part of our internal team. You always jump to asking for all the developers code. Also, based on your documentation and the documentation of the `vite-plugin-pages` plugin, the code above should be all the code needed.

That being said, considering this has come up multiple times with the same answer or no answer, there's either a disconnect with your documentation and examples or the plugin is broken. Are there some special commands or something that we have to run? When should the sitemap be generator because I think most of us are expecting the sitemap to be generated as soon as we run the build (`npm run build`). Is there something else we need to do?

**Comment by jbaubree** [comment] 2023-09-06 05:50
I need to see more than vite.config to understand why this is not working as expected. I don't want specialy your codebas but just a [minimal reproduction](https://en.m.wikipedia.org/wiki/Minimal_reproducible_example)  for easyer débug.

If you say me that you can't provide me one, i have more questions, can you share me you main.ts with vite-plugin-pages configuration? Are you running `npm run dev`? Do you have a public folder?

**Comment by recoiladam** [comment] 2023-09-06 05:54
What additional code do you need? Your documentation specifically says to add to `vite.config.js`, nothing more, nothing less. As for the `vite-plugin-pages` plugin, it does not say anything needs to be added anywhere else either. If more code needs to be added somewhere, then the documentation should be updated.

I am not using Typescript, I am using Javascript as that is what I prefer. My `main.js` is below though it is redacted:

```
import { createApp } from 'vue'
import { createGtm } from '@gtm-support/vue-gtm'
import { createHead } from '@vueuse/head'
import App from '@/app.vue'
import Router from '@/router'

const app = createApp(App).use(Router).use(createHead())

Router.isReady().then(() => {
  app.mount('#app')
})
```

Here are my scripts from the `package.json` file:

```
  "scripts": {
    "serve": "vite --config vite.config.js",
    "build": "vite build --config vite.config.js",
    "preview": "vite preview",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix src --ignore-path .gitignore",
    "format": "prettier .  --write"
  },
```

When I run the code base locally, I use `npm run serve`. When I run the build, I use `npm run build`.

**Comment by jbaubree** [comment] 2023-09-06 05:59
Well... Are you generating your routes in @/router with vite-vite-plugin-pages?

**Comment by recoiladam** [comment] 2023-09-06 06:01
> Well... Are you generating your routes in @/router with vite-vite-plugin-pages?

Nope, I was trying to supply them manually like the documentation says I can. Look at the config I provided previously.

```
routes: ['/', '/about', '/analytics', '/imagery', '/contact', '/team', '/privacy', '/terms'],
```

Your documentation says I should be able to do this. If routes MUST be generated dynamically, perhaps the documentation should specifically state this and not show an example using an array of strings.

**Comment by jbaubree** [comment] 2023-09-06 06:14
Ok this is the reason that sitemap generating is not working. README says `vite-plugin-pages based sitemap generator` i thinked that it was understable that you need to use vite-plugin-pages at the same time. I will add a notice for that in README. Thanks for your feedbacks.

In your situation, i recommend you to use [vite-plugin-sitemap](https://github.com/jbaubree/vite-plugin-sitemap) ☺️

**Comment by recoiladam** [comment] 2023-09-06 06:18
> Ok this is the reason that sitemap generating is not working. README says `vite-plugin-pages based sitemap generator` i thinked that it was understable that you need to use vite-plugin-pages at the same time. I will add a notice for that in README. Thanks for your feedbacks.
> 
> In your situation, i recommend you to use [vite-plugin-sitemap](https://github.com/jbaubree/vite-plugin-sitemap) ☺️

Yes, I would recommend updating the documentation because it does show an example using an array of strings which throws people off since generating the routes with `vite-plugin-pages` is required.

As for the `vite-plugin-sitemap` plugin, I will give it a try. Thank you.

**Comment by jbaubree** [comment] 2023-09-06 06:59
@recoiladam i have updated [README](https://github.com/jbaubree/vite-plugin-pages-sitemap/blob/main/README.md) with a warning for vite-plugin-pages use. If all is good for you, feel free to close this issue. If you need more help, you can contact me at `jb.aubree@protonmail.com`, i will be very happy to help you.

**Closed** 2023-09-08 13:56 UTC
