### ISSUE TITLE
Sitemap.xml has not been generated

### ISSUE THREAD

**Issue by ooralas** [jbaubree/vite-plugin-pages-sitemap#140] opened 2022-08-30 16:15 UTC
Hi,
the plug-in cannot generate sitemap for my website, i am building my website as following :
```json
"dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-helmet": "^6.1.0",
    "react-router-dom": "^6.3.0",
    "zustand": "^4.0.0-rc.1"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^1.3.0",
    "sass": "^1.52.3",
    "vite": "^3.0.9",
    "vite-plugin-pages": "^0.25.0",
    "vite-plugin-pages-sitemap": "^1.3.0"
  }
```

the `.jsx` which are the single pages are located in the src/views. Then i run `npm run build` to build the website, but i get nothing.  my vite.config.js look like so: 
```Javascript 
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import Pages from 'vite-plugin-pages'
import generateSitemap from 'vite-plugin-pages-sitemap'

export default defineConfig({
  plugins: [
    react(),
    Pages({
      dirs: 'src/views',
      onRoutesGenerated: routes =>
        generateSitemap({
          routes,
          readable: true,
          dest: 'public',
          filename: 'sitemap.xml'
        }),
    }),
  ],
  server: {
    host: true,
  },
})

```

**Comment by jbaubree** [comment] 2022-09-03 10:41
Heyy, this plugin generate your sitemap and robots files on dev mode. Please run `npm run dev` ans open your localhost page before building app

**Comment by ooralas** [comment] 2022-09-06 10:54
Hey @jbaubree, thanks for your reply.
I did run the `npm run dev` command, but i got no new files in  `dist` directory, I tried to request `{myhost}/sitmap`  I got my `NotFound`-Page.

**Comment by jbaubree** [comment] 2022-09-06 11:12
@ooralas when you run dev and open localhost, this will create files in your `public` folder. Next when you run `build`, public folder content will go into `dist` directory. You will be able to access `{myhost}/sitemap.xml` on production only

**Comment by ooralas** [comment] 2022-09-06 11:19
i got nothing also in `public`

**Comment by jbaubree** [comment] 2022-09-06 17:10
@ooralas can you provide a repo with reproduction ?

**Comment by ooralas** [comment] 2022-09-13 23:38
@jbaubree so i prepared a repo, which is similar to my my project in folder structure, and i served the site on netlify.
Here is a link to the repo --> https://github.com/ooralas/testsitemapgenerator
and the link to the site --> https://testsitemapgenerator.netlify.app/

**Comment by jbaubree** [comment] 2022-09-14 09:12
@ooralas In your repo, onRoutesGenerated hook does not work.
You need to follow [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages#react-1) documentation and use `react-router`.

```
npm install react-router
```

In your main.jsx

```
import { Suspense } from 'react'
import {
  BrowserRouter as Router,
  useRoutes,
} from 'react-router-dom'

import routes from '~react-pages'

const App = () => {
  return (
    <Suspense fallback={<p>Loading...</p>}>
      {useRoutes(routes)}
    </Suspense>
  )
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <Router>
    <App />
  </Router>
)
```

and use generateSitemap default export in your vite.config.js:
```
export default defineConfig({
  plugins: [
    Pages({
      onRoutesGenerated: routes => {
        generateSitemap.default({
          ...
        })
      }
    }),
  ],
})
```

**Comment by ooralas** [comment] 2022-09-14 16:09
Unfortunately, it didn't work. `useRoute(routes)` or the way i implemented my routes in `<App />` are actually the same, see https://reactrouter.com/en/main/hooks/use-routes

**Comment by jbaubree** [comment] 2022-09-14 16:33
@ooralas the fact is that when you use your routes in `<App />`, vite-plugin-pages hooks like onGeneratedRoutes are not called. You can open an issue on [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages/issues/new/choose) and deal with @hannoeru to get hooks working. This will fix your sitemap generation

**Comment by jbaubree** [comment] 2022-09-20 13:06
Closing because this is not a `vite-plugin-pages-sitemap` issue. If you want some help, contact me by email jb.aubree@protonmail.com

**Closed by jbaubree** 2022-09-20 13:06 UTC
Labels: need reproduction
